import { readFileSync } from "fs";
import path from "path";
import ts from "typescript";

// Mocha BDD interface identifiers. `describe`/`context` are aliases; same for
// `it`/`specify`. We treat `xdescribe`/`xit`/`describe.skip`/`it.only` as the
// same kind — pending/exclusive markers don't change the tree shape, just the
// title display.
const SUITE_NAMES = new Set(["describe", "context", "xdescribe"]);
const TEST_NAMES = new Set(["it", "specify", "xit"]);

export type NodeKind = "describe" | "it";

export interface SuiteNode {
    kind: NodeKind;
    title: string;
    // Mocha's joined full title: parent ' ' + this.title (root = "").
    fullTitle: string;
    // 1-based line range that the UI uses to slice source for read-only preview.
    line: number;
    endLine: number;
    children: SuiteNode[];
    pending?: boolean;
    only?: boolean;
}

export interface SuiteTree {
    file: string;          // absolute path
    relPath: string;       // relative to cwd
    children: SuiteNode[]; // top-level describes/its
    // Full file source for read-only preview slicing. Omitted when the file
    // failed to read (in which case `error` will be set).
    source?: string;
    error?: string;        // populated when the parse failed; tree still usable
}

export interface ParseOptions {
    cwd: string;
}

// Best-effort parser. Goals:
//   * No execution — pure AST walk, never `require()`s the spec.
//   * Capture static-string titles literally; flag dynamic titles as "<dynamic>"
//     so the UI can still render the position but the user knows --grep can't
//     target it precisely.
//   * Recognize describe.skip / it.only / xit / xdescribe as pending/only markers.
//
// What it DOES NOT capture (deliberate): tests created inside loops or
// `forEach` callbacks at top level. Those are dynamic and Mocha only knows
// about them after the file is required. The user can still run the whole
// file by selecting the file node.
export function parseSuiteTree(absPath: string, opts: ParseOptions): SuiteTree {
    const relPath = path.relative(opts.cwd, absPath).split(path.sep).join("/");
    let source: string;
    try {
        source = readFileSync(absPath, "utf8");
    } catch (e: any) {
        return { file: absPath, relPath, children: [], error: e?.message ?? String(e) };
    }

    const ext = path.extname(absPath).toLowerCase();
    const scriptKind =
        ext === ".tsx" ? ts.ScriptKind.TSX :
        ext === ".ts" ? ts.ScriptKind.TS :
        ext === ".jsx" ? ts.ScriptKind.JSX :
        ts.ScriptKind.JS;

    const sf = ts.createSourceFile(absPath, source, ts.ScriptTarget.Latest, /*setParentNodes*/ false, scriptKind);

    const out: SuiteNode[] = [];

    function visit(node: ts.Node, parentFullTitle: string, dest: SuiteNode[]): void {
        if (ts.isCallExpression(node)) {
            const info = classifyCall(node);
            if (!info) {
                // Plain function call. Do NOT descend — we only want tests
                // statically nested in describe blocks, not ones generated by
                // arbitrary callbacks (forEach, custom helpers, IIFEs).
                return;
            }
            const titleArg = node.arguments[0];
            const bodyArg = node.arguments[node.arguments.length - 1];
            const title = extractTitle(titleArg);
            const fullTitle = parentFullTitle === "" ? title : `${parentFullTitle} ${title}`;
            const { line: startLine } = sf.getLineAndCharacterOfPosition(node.getStart(sf));
            const { line: endLine } = sf.getLineAndCharacterOfPosition(node.getEnd());
            const child: SuiteNode = {
                kind: info.kind,
                title,
                fullTitle,
                line: startLine + 1,
                endLine: endLine + 1,
                children: [],
                ...(info.pending ? { pending: true } : {}),
                ...(info.only ? { only: true } : {}),
            };
            dest.push(child);
            if (info.kind === "describe" && bodyArg && (ts.isFunctionExpression(bodyArg) || ts.isArrowFunction(bodyArg))) {
                if (bodyArg.body && ts.isBlock(bodyArg.body)) {
                    for (const stmt of bodyArg.body.statements) {
                        visit(stmt, fullTitle, child.children);
                    }
                }
            }
            return;
        }
        // Structural / wrapper node (ExpressionStatement, ParenthesizedExpression,
        // VariableStatement, IfStatement, ...). Descend so we find a describe/it
        // wrapped in non-call constructs, but the recursion stops as soon as we
        // hit any CallExpression (handled above).
        ts.forEachChild(node, (n) => visit(n, parentFullTitle, dest));
    }

    for (const stmt of sf.statements) {
        visit(stmt, "", out);
    }

    return { file: absPath, relPath, source, children: out };
}

interface CallInfo {
    kind: NodeKind;
    pending: boolean;
    only: boolean;
}

function classifyCall(node: ts.CallExpression): CallInfo | null {
    // describe(...), it(...), context(...), specify(...), xit(...), xdescribe(...)
    if (ts.isIdentifier(node.expression)) {
        const n = node.expression.text;
        if (SUITE_NAMES.has(n)) return { kind: "describe", pending: n === "xdescribe", only: false };
        if (TEST_NAMES.has(n)) return { kind: "it", pending: n === "xit", only: false };
        return null;
    }
    // describe.skip(...), describe.only(...), it.skip(...), it.only(...)
    if (ts.isPropertyAccessExpression(node.expression) && ts.isIdentifier(node.expression.expression)) {
        const root = node.expression.expression.text;
        const prop = node.expression.name.text;
        if (SUITE_NAMES.has(root)) {
            return { kind: "describe", pending: prop === "skip", only: prop === "only" };
        }
        if (TEST_NAMES.has(root)) {
            return { kind: "it", pending: prop === "skip", only: prop === "only" };
        }
    }
    return null;
}

function extractTitle(arg: ts.Expression | undefined): string {
    if (!arg) return "<missing>";
    if (ts.isStringLiteral(arg) || ts.isNoSubstitutionTemplateLiteral(arg)) return arg.text;
    // Template literal with no substitutions handled above; with substitutions
    // the title is dynamic — emit a marker so the UI shows position without
    // claiming a runnable grep target.
    return "<dynamic>";
}

// Build a Mocha --grep regex string for a given selection. Mocha treats
// --grep as `new RegExp(value)`, so we anchor with ^ and escape regex
// metacharacters. For a `describe` node we want every `it` whose full title
// starts with the describe's title plus a space (so a sibling describe with
// the same prefix doesn't match).
//
// Returns null if title is empty or marked dynamic — caller should run the
// whole file in that case.
export function mochaGrepFor(node: { kind: NodeKind; fullTitle: string }): string | null {
    if (!node.fullTitle || node.fullTitle.includes("<dynamic>") || node.fullTitle.includes("<missing>")) {
        return null;
    }
    const escaped = escapeRegex(node.fullTitle);
    return node.kind === "it" ? `^${escaped}$` : `^${escaped} `;
}

export function escapeRegex(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
